"""init tables

Revision ID: 021f26ceb3ef
Revises: 
Create Date: 2026-09-15 12:53:47.216961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021f26ceb3ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name_cn', sa.String(length=128), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('cik', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ticker'), 'stock', ['ticker'], unique=True)
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'form_type', 'fiscal_year', name='uq_analysis')
    )
    op.create_table('dcf_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('growth', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('years', sa.Integer(), nullable=True),
    sa.Column('safety', sa.Float(), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.Column('valuation', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=True),
    sa.Column('accession_no', sa.String(length=32), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'form_type', 'period', name='uq_filing')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('log_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_table('task')
    op.drop_table('filing')
    op.drop_table('dcf_report')
    op.drop_table('analysis')
    op.drop_index(op.f('ix_stock_ticker'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
